version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - grpc-net
    volumes:
      - mongo-data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "50051:50051"
    depends_on:
      - mongo
    networks:
      - grpc-net

  inventory-service:
    build: ./inventory-service
    ports:
      - "50052:50052"
    networks:
      - grpc-net

  order-service:
    build: ./order-service
    ports:
      - "50053:50053"
    depends_on:
      - mongo
      - nats
    networks:
      - grpc-net
    environment:
      - NATS_URL=nats://nats:4222

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - inventory-service
      - order-service
    networks:
      - grpc-net

  nats:
    image: nats:latest
    container_name: nats
    hostname: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - grpc-net
    restart: always

volumes:
  mongo-data:

networks:
  grpc-net:
